import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { BreadcrumbJsonLd } from "@/components/breadcrumb-jsonld";
import { Link } from "@/i18n/navigation";
import { alternates, og } from "@/lib/seo";
import { CURRENT_SITE_URL } from "@/lib/sites";
import { FrpWeightCalculator } from "./calculator";
export const metadata: Metadata = { title: { absolute: "FRP Weight Calculator — Profiles, Rods, Tubes & Panels | getfrp" }, description: "Estimate FRP profile, rod, tube and panel weight from density and geometric volume, with typical fiberglass and carbon composite densities.", alternates: alternates("/tools/frp-weight-calculator"), openGraph: og("/tools/frp-weight-calculator", { title: "FRP Weight Calculator", description: "Estimate composite mass from density and volume." }) };
export default async function WeightCalculatorPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; setRequestLocale(locale); return <main><BreadcrumbJsonLd items={[{ name: "Home", url: `${CURRENT_SITE_URL}/` }, { name: "Tools", url: `${CURRENT_SITE_URL}/tools` }, { name: "FRP weight calculator", url: `${CURRENT_SITE_URL}/tools/frp-weight-calculator` }]} /><section className="border-b"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><nav className="text-xs text-muted-foreground"><Link href="/">Home</Link><span className="mx-2">›</span><Link href="/tools">Tools</Link><span className="mx-2">›</span><span>FRP weight calculator</span></nav><h1 className="mt-7 text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">FRP Weight Calculator</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">Estimate fiberglass or carbon composite weight using the transparent relation mass = density × volume. Use supplier-confirmed density and the net section area for purchasing.</p><div className="mt-9"><FrpWeightCalculator /></div></div></section><section className="border-b"><div className="mx-auto max-w-4xl px-4 py-14 sm:px-6"><h2 className="text-2xl font-semibold">How to calculate FRP weight</h2><div className="mt-5 space-y-4 text-[15px] leading-7 text-muted-foreground"><p>Convert the cross-sectional area to square metres, multiply it by length to obtain volume, then multiply by density in kilograms per cubic metre. A 100 mm × 10 mm solid profile has an area of 1,000 mm², or 0.001 m². At 1,850 kg/m³, one metre is approximately 1.85 kg.</p><p>Published density values are useful estimates, not acceptance values. Glass content, resin, fillers, veil and voids change mass. Hollow profiles also have radii, wall variation and internal webs that a simple rectangle or tube cannot capture. For freight, add packaging and use the supplier&apos;s measured linear mass from an approved production sample.</p><p>This FRP weight calculator does not check strength, deflection, stability, fire, connections or code compliance. Use project calculations and current supplier data before design or purchase.</p></div><div className="mt-7 flex flex-wrap gap-2"><Link href="/products/pultruded-profiles" className="rounded-full border px-4 py-2 text-sm">Pultruded profiles</Link><Link href="/products/frp-rebar" className="rounded-full border px-4 py-2 text-sm">FRP rebar</Link><Link href="/tools/standard-comparison" className="rounded-full border px-4 py-2 text-sm">Standard comparison</Link></div></div></section></main>; }
