import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { ArrowRight } from "lucide-react";
import { BreadcrumbJsonLd } from "@/components/breadcrumb-jsonld";
import { buttonVariants } from "@/components/ui/button";
import { Link } from "@/i18n/navigation";
import { HELP_PAGES } from "@/lib/data/help-pages";
import { alternates, og } from "@/lib/seo";
import { CURRENT_SITE_URL } from "@/lib/sites";
function find(slug: string) { return HELP_PAGES.find((page) => page.slug === slug) ?? null; }
export function generateStaticParams() { return HELP_PAGES.map(({ slug }) => ({ topic: slug })); }
export async function generateMetadata({ params }: { params: Promise<{ topic: string }> }): Promise<Metadata> { const { topic } = await params; const page = find(topic); if (!page) return { robots: { index: false, follow: true } }; const path = `/help/${page.slug}`; return { title: { absolute: `${page.title} | getfrp` }, description: page.description, alternates: alternates(path), openGraph: og(path, { title: page.title, description: page.description }) }; }
export default async function HelpTopicPage({ params }: { params: Promise<{ locale: string; topic: string }> }) { const { locale, topic } = await params; setRequestLocale(locale); const page = find(topic); if (!page) notFound(); const url = `${CURRENT_SITE_URL}/help/${page.slug}`; return <main><BreadcrumbJsonLd items={[{ name: "Home", url: `${CURRENT_SITE_URL}/` }, { name: "Help", url: `${CURRENT_SITE_URL}/help/how-to-search-suppliers` }, { name: page.title, url }]} /><section className="border-b"><div className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><nav className="text-xs text-muted-foreground"><Link href="/">Home</Link><span className="mx-2">›</span><span>Help</span><span className="mx-2">›</span><span>{page.title}</span></nav><h1 className="mt-7 text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">{page.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{page.description}</p></div></section><section className="border-b"><div className="mx-auto max-w-4xl px-4 py-14 sm:px-6"><ol className="space-y-5">{page.steps.map((step, index) => <li key={step} className="grid grid-cols-[44px_1fr] gap-4 rounded-xl border p-5"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-foreground font-mono text-sm text-background">{index + 1}</div><div><h2 className="font-semibold">Step {index + 1}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{step}</p></div></li>)}</ol><div className="mt-8 flex flex-wrap gap-3"><Link href="/suppliers" className={buttonVariants({ size: "lg", variant: "outline" })}>Search suppliers</Link><Link href="/rfq" className={buttonVariants({ size: "lg" })}>Send an RFQ <ArrowRight size={15} /></Link></div></div></section><section className="bg-muted/15"><div className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><h2 className="text-xl font-semibold">More help</h2><div className="mt-5 flex flex-wrap gap-2">{HELP_PAGES.filter((item) => item.slug !== page.slug).map((item) => <Link key={item.slug} href={`/help/${item.slug}` as never} className="rounded-full border bg-background px-4 py-2 text-sm">{item.title}</Link>)}</div></div></section></main>; }
