import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { or, ilike } from "drizzle-orm";
import {
  BookOpen,
  ArrowRight,
  ChevronRight,
} from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { db } from "@/lib/db";
import { formulas as formulasTable } from "@/lib/db/schema";
import {
  parseCombo,
  findFiber,
  findResin,
  allComboSlugs,
  comboFeasibility,
  MATRIX_REVIEWED,
  PROCESSES,
  type Fiber,
  type Resin,
} from "@/lib/data/matrix";
import { alternates, og } from "@/lib/seo";
import { CURRENT_SITE_URL } from "@/lib/sites";
import { JsonLd } from "@/components/json-ld";
import { BreadcrumbJsonLd } from "@/components/breadcrumb-jsonld";
import {
  PlatformHero,
  PlatformSectionHeading,
} from "@/components/platform-card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";

export const revalidate = 600;

// Pre-render all 55 canonical fiber×resin combos at build (SSG), then keep them
// fresh with ISR. Locale is generated by the [locale] layout, so we only return
// the [combo] segment here (same pattern as fibers/[slug]).
export function generateStaticParams() {
  return allComboSlugs().map((combo) => ({ combo }));
}

// Build ILIKE `or` across the given text columns for any of the keywords.
// Cast is fine — we only call this with known matching columns on each table.
function keywordOr(
  _table: unknown,
  keywords: string[],
  cols: Array<unknown>
) {
  const ors = keywords.flatMap((k) =>
    cols
      .filter(Boolean)
      .map((c) => ilike(c as never, `%${k}%`))
  );
  return or(...(ors as never[]));
}

async function searchFormulas(fiber: Fiber, resin: Resin, limit = 12) {
  try {
    const cols = [
      formulasTable.name,
      formulasTable.description,
      formulasTable.application,
    ];
    return await db
      .select({
        id: formulasTable.id,
        name: formulasTable.nameEn,
        process: formulasTable.processEn,
        application: formulasTable.applicationEn,
      })
      .from(formulasTable)
      .where(keywordOr(null, [...fiber.keywords, ...resin.keywords], cols))
      .limit(limit);
  } catch {
    return [];
  }
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; combo: string }>;
}): Promise<Metadata> {
  const { locale, combo } = await params;
  const noindex = { robots: { index: false, follow: false } };
  const parsed = parseCombo(combo);
  if (!parsed) return { title: "Not found", ...noindex };
  const fiber = findFiber(parsed.fiberSlug);
  const resin = findResin(parsed.resinSlug);
  if (!fiber || !resin) return { title: "Not found", ...noindex };
  const t0 = await getTranslations({ locale, namespace: "Platform.Matrix.Combo" });
  const name =
    locale === "en"
      ? `${fiber.nameEn} × ${resin.nameEn}`
      : `${fiber.name} × ${resin.name}`;
  const title = t0("metaTitle", { name });
  const description = t0("metaDescription", { name });
  return {
    title,
    description,
    robots: { index: false, follow: true },
    // Path-aware GetFRP canonical. This English-only site never emits a
    // cross-domain or Chinese hreflang alternate.
    alternates: alternates(`/matrix/${combo}`),
    openGraph: og(`/matrix/${combo}`, { title, description }),
  };
}

export default async function ComboPage({
  params,
}: {
  params: Promise<{ locale: string; combo: string }>;
}) {
  const { locale, combo } = await params;
  setRequestLocale(locale);
  const parsed = parseCombo(combo);
  if (!parsed) notFound();
  const fiber = findFiber(parsed.fiberSlug);
  const resin = findResin(parsed.resinSlug);
  if (!fiber || !resin) notFound();

  // Use namespace Matrix.Combo so keys stay colocated with the parent Matrix page.
  const t = await getTranslations({ locale, namespace: "Platform.Matrix.Combo" });

  const formulas = await searchFormulas(fiber, resin);

  const fiberName = locale === "en" ? fiber.nameEn : fiber.name;
  const resinName = locale === "en" ? resin.nameEn : resin.name;
  const displayName = `${fiberName} × ${resinName}`;

  // Feasibility verdict — the Consensus-Meter analog, grounded in the
  // FEASIBILITY matrix (deterministic engineering data, not opinion polling).
  const score = comboFeasibility(parsed.fiberSlug, parsed.resinSlug);
  const url = `${CURRENT_SITE_URL}/matrix/${combo}`;
  const verdictLabel =
    score === 2 ? t("verdictLabel2") : score === 1 ? t("verdictLabel1") : t("verdictLabel0");
  const verdictAnswer =
    score === 2
      ? t("verdictAnswer2", { fiber: fiberName, resin: resinName })
      : score === 1
        ? t("verdictAnswer1", { fiber: fiberName, resin: resinName })
        : t("verdictAnswer0", { fiber: fiberName, resin: resinName });
  const verdictCls =
    score === 2
      ? "bg-foreground text-background"
      : score === 1
        ? "border border-border bg-muted text-foreground"
        : "border border-dashed border-muted-foreground/50 text-muted-foreground";
  const verdictDot = score === 2 ? "●" : score === 1 ? "○" : "·";

  // Answer-first Q&A → visible FAQ + FAQPage schema (Google requires the
  // schema's answers to be visible on the page, which they are below).
  const faqItems = [
    { q: t("faqQ1", { fiber: fiberName, resin: resinName }), a: verdictAnswer },
    { q: t("faqQ2", { fiber: fiberName, resin: resinName }), a: t("faqA2") },
    { q: t("faqQ3", { fiber: fiberName, resin: resinName }), a: t("faqA3") },
  ];
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": `${url}#faq`,
    mainEntity: faqItems.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20">
      <BreadcrumbJsonLd
        items={[
          { name: t("breadcrumb"), url: `${CURRENT_SITE_URL}/matrix` },
          { name: displayName, url },
        ]}
      />
      <JsonLd data={faqSchema} />

      <nav className="mb-6 text-xs text-muted-foreground">
        <Link href="/matrix" className="hover:text-foreground">
          {t("breadcrumb")}
        </Link>
        <span className="mx-1.5">/</span>
        <span>{displayName}</span>
      </nav>

      <PlatformHero
        eyebrow={`${fiber.mono} × ${resin.mono}`}
        title={displayName}
        description={t("lead", { fiber: fiberName, resin: resinName })}
      />

      {/* Feasibility verdict — answer-first, from the FEASIBILITY matrix */}
      <section className="mb-10 rounded-lg border bg-muted/20 p-6">
        <div className="flex flex-wrap items-center gap-3">
          <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
            {t("verdictTitle")}
          </span>
          <span
            className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-semibold ${verdictCls}`}
          >
            <span className="font-mono">{verdictDot}</span>
            {verdictLabel}
          </span>
        </div>
        <p className="mt-3 max-w-3xl text-[15px] leading-relaxed text-foreground/90">
          {verdictAnswer}
        </p>
        <div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-muted-foreground">
          <span>
            <span className="text-foreground/70">{t("verdictSourceLabel")}:</span>{" "}
            {t("verdictSource")}
          </span>
          <span className="text-muted-foreground/40">·</span>
          <span>
            {t("verdictUpdatedLabel")} {MATRIX_REVIEWED}
          </span>
        </div>
      </section>

      {/* Live stats from DB */}
      <div className="mb-10">
        <div className="rounded-lg border bg-background p-4 text-center">
          <div className="text-2xl font-bold tabular-nums">{formulas.length}</div>
          <div className="mt-1 text-xs text-muted-foreground">{t("statFormulas")}</div>
        </div>
      </div>

      {/* Process chips as a third axis */}
      <section className="mb-12">
        <PlatformSectionHeading eyebrow={t("processesLabel")} title={t("processesTitle")} />
        <div className="flex flex-wrap gap-2">
          {PROCESSES.map((p) => (
            <Badge
              key={p.slug}
              variant="outline"
              className="px-3 py-1.5 font-mono text-[11px] uppercase tracking-[0.14em]"
            >
              {p.mono}
            </Badge>
          ))}
        </div>
        <p className="mt-3 text-xs text-muted-foreground">{t("processesHint")}</p>
      </section>

      <section className="mb-12 grid gap-3 sm:grid-cols-2">
        <Link
          href="/products"
          className="group rounded-lg border bg-background p-5 transition-colors hover:border-primary/40"
        >
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
            PRODUCT DATABASE
          </div>
          <div className="mt-2 flex items-center justify-between gap-3 font-semibold">
            Compare FRP product specifications
            <ArrowRight size={15} className="transition-transform group-hover:translate-x-0.5" />
          </div>
        </Link>
        <Link
          href="/suppliers"
          className="group rounded-lg border bg-background p-5 transition-colors hover:border-primary/40"
        >
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
            SUPPLIER DATABASE
          </div>
          <div className="mt-2 flex items-center justify-between gap-3 font-semibold">
            Find qualified FRP manufacturers
            <ArrowRight size={15} className="transition-transform group-hover:translate-x-0.5" />
          </div>
        </Link>
      </section>

      {/* Formulas */}
      {formulas.length > 0 && (
        <section className="mb-12">
          <PlatformSectionHeading eyebrow="FORMULAS" title={t("formulaTitle")} />
          <div className="grid gap-2 md:grid-cols-2">
            {formulas.map((f) => (
              <div
                key={f.id}
                className="rounded-md border bg-background p-3 text-sm"
              >
                <div className="mb-1 flex flex-wrap items-center gap-1.5">
                  {f.process && (
                    <Badge variant="outline" className="text-[10px]">
                      {f.process}
                    </Badge>
                  )}
                  {f.application && (
                    <span className="text-[10px] text-muted-foreground">
                      {f.application}
                    </span>
                  )}
                </div>
                <div className="line-clamp-2 font-medium">{f.name}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      {formulas.length === 0 && (
          <section className="rounded-lg border bg-muted/30 p-10 text-center">
            <p className="text-sm text-muted-foreground">
              {t("emptyBody", { name: displayName })}
            </p>
          </section>
        )}

      {/* FAQ — visible Q&A backing the FAQPage schema above */}
      <section className="mt-16">
        <div className="mb-5 flex items-center gap-2 border-b border-border/70 pb-2">
          <BookOpen size={16} className="text-muted-foreground" />
          <h2 className="text-xl font-semibold tracking-tight sm:text-2xl">
            {t("faqTitle")}
          </h2>
        </div>
        <div className="divide-y divide-border/70 border-y border-border/70">
          {faqItems.map((f) => (
            <details
              key={f.q}
              className="group cursor-pointer py-4 [&_summary::-webkit-details-marker]:hidden"
            >
              <summary className="flex items-start justify-between gap-3">
                <span className="text-[15px] font-semibold leading-snug tracking-tight">
                  {f.q}
                </span>
                <ChevronRight
                  size={14}
                  className="mt-1 shrink-0 text-muted-foreground transition-transform group-open:rotate-90"
                />
              </summary>
              <p className="mt-3 max-w-3xl text-[14px] leading-[1.8] text-muted-foreground">
                {f.a}
              </p>
            </details>
          ))}
        </div>
      </section>

      {/* Next step — B2B conversion path (RFQ / suppliers / calculator) */}
      <section className="mt-12">
        <div className="mb-4 font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
          {t("nextStepLabel")}
        </div>
        <div className="grid gap-3 sm:grid-cols-3">
          <Link
            href={`/rfq?combo=${encodeURIComponent(combo)}` as never}
            className="group flex items-center justify-between gap-3 rounded-md border bg-foreground p-4 text-sm font-semibold text-background transition-colors hover:bg-foreground/90"
          >
            {t("ctaRfqTitle")}
            <ArrowRight size={15} className="shrink-0" />
          </Link>
          <Link
            href={"/suppliers/search?profile=verified" as never}
            className="group flex items-center justify-between gap-3 rounded-md border bg-background p-4 text-sm font-medium transition-colors hover:border-primary/40 hover:bg-muted/30"
          >
            {t("ctaSuppliersTitle")}
            <ChevronRight
              size={15}
              className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5"
            />
          </Link>
          <Link
            href={"/tech/calculator" as never}
            className="group flex items-center justify-between gap-3 rounded-md border bg-background p-4 text-sm font-medium transition-colors hover:border-primary/40 hover:bg-muted/30"
          >
            {t("ctaCalcTitle")}
            <ChevronRight
              size={15}
              className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5"
            />
          </Link>
        </div>
      </section>

      {/* AI CTA */}
      <section className="mt-12 rounded-lg border bg-muted/30 p-8 text-center">
        <h3 className="text-lg font-semibold">{t("aiCtaTitle")}</h3>
        <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
          {t("aiCtaBody", { name: displayName })}
        </p>
        <div className="mt-4">
          <Link
            href={
              `/ai?q=${encodeURIComponent(
                t("aiSuggestQuery", { fiber: fiberName, resin: resinName })
              )}` as never
            }
            className={buttonVariants({ size: "lg" })}
          >
            {t("aiCtaBtn")}
          </Link>
        </div>
      </section>
    </div>
  );
}
