// One-off generator: produces curated long-form bodies for each news item
// in src/lib/data/news.ts via Gemini, then writes them to
// src/lib/data/article-bodies.ts. Re-run only when news list changes.
//
// Run: pnpm tsx --env-file=.env.local scripts/gen-article-bodies.ts

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText } from "ai";
import { newsList, type NewsItem } from "../src/lib/data/news";

for (const envPath of [".env.local", ".env"]) {
  if (!existsSync(envPath)) continue;
  for (const line of readFileSync(envPath, "utf-8").split("\n")) {
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    const [, key, raw] = m;
    if (process.env[key]) continue;
    let value = raw.trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    process.env[key] = value;
  }
}

if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
  console.error("Missing GOOGLE_GENERATIVE_AI_API_KEY");
  process.exit(1);
}

const google = createGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
});

const SYSTEM = `你是复材站的资深行业编辑，专长把零散的行业资讯改写成对 B2B 工程师/采购/企业决策者有价值的深度整理稿。

写作原则（在线营销逻辑，但不是软文）：
1. 先抛出让读者停下的"痛点/机会"钩子，避免"最近…发布了…"式平铺开头
2. 用小标题 + 段落组织，3-5 个二级小标题（Markdown ## ）
3. 每个小标题下给出具体数据/案例/机理解释，避免空话
4. 结尾加一段"对行业意味着什么"的实用结论（2-4 条要点），帮助读者形成判断
5. 最后一段点明可以在复材站查到的相关资源（材料库/标准库/供应商/AI 问答）— 柔性引导，不硬推销
6. 1000-1400 字；不要复述标题；不要写"综上所述"；不要编造具体人名或私企未公开数据
7. 语言：简体中文，第三人称中立，工程师能读得进去

严禁：
- 凭空编造联系方式、价格、厂商负责人名
- 复制粘贴式的原文引用（只做事实性转述）
- 虚假统计数据（不确定的数值用"约/行业估算"等措辞）

输出格式（纯正文，不要前后包裹代码块）：
---
**整理自网络公开资料**

> （一两句导语钩子）

## （小标题1）
正文…

## （小标题2）
正文…

## 对行业意味着什么
- …
- …

## 在复材站继续研究
（柔性引导到 /products /sourcing/gb-vs-astm-frp /suppliers /ai 等内部路径）

---
`;

async function genBody(item: NewsItem): Promise<string> {
  const userPrompt = `请围绕以下资讯改写成深度整理稿：

标题：${item.title}
摘要：${item.summary}
分类：${item.category}
日期：${item.date}

按系统提示的格式输出正文。`;
  const { text } = await generateText({
    model: google("gemini-2.5-flash"),
    system: SYSTEM,
    prompt: userPrompt,
    maxOutputTokens: 4000,
  });
  return text.trim();
}

async function main() {
  const results: Array<{ id: string; body: string }> = [];
  for (const item of newsList) {
    process.stdout.write(`✍️  ${item.id} ${item.title.slice(0, 30)}… `);
    let body = "";
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        body = await genBody(item);
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        process.stdout.write(`attempt ${attempt} FAILED: ${msg}; `);
        continue;
      }
      if (body.length >= 1200) break;
      process.stdout.write(`attempt ${attempt} short (${body.length}); `);
    }
    if (body.length < 400) body = item.summary;
    results.push({ id: item.id, body });
    process.stdout.write(`${body.length} chars ✓\n`);
  }

  const out = `// AUTO-GENERATED by scripts/gen-article-bodies.ts
// Do not edit by hand — re-run the generator instead.
// Source: Gemini 2.5 Flash, prompted with the marketing-editorial system prompt.

export const articleBodies: Record<string, string> = {
${results
  .map(
    (r) =>
      `  ${JSON.stringify(r.id)}: ${JSON.stringify(r.body)},`
  )
  .join("\n")}
};
`;
  const outPath = resolve(process.cwd(), "src/lib/data/article-bodies.ts");
  writeFileSync(outPath, out, "utf-8");
  console.log(`\n✅ Wrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
